In [1]:
import numpy as np
import torch
from torch.nn.functional import conv2d as libConv2d
import pytest

In [4]:
%%file conv2D.py
import numpy as np

def conv2D(input_tensor, weight_tensor, padding=0, dilation=1, stride=1, groups = 1):
    # Get input dimensions
    image_height, image_width  = input_tensor.shape
    weight_height, weight_width  = weight_tensor.shape

    # Calculate output dimensions
    H_out = int((image_height - weight_height + 2 * padding) / stride) + 1
    W_out = int((image_width - weight_width + 2 * padding) / stride) + 1

    #создание результирующего изображения
    result = np.zeros((H_out, W_out))
    #добавление padding (добавление нулей вокруг входной матрицы)
    if padding > 0:
        input_tensor = np.pad(input_tensor, padding, mode='constant')
    #проход ядром по изображению
    for y in range(H_out):
        for x in range(W_out):
            result[y, x] = np.sum(input_tensor[y*stride:y*stride+weight_height, x*stride:x*stride+weight_width] * weight_tensor)
    return result

Overwriting conv2D.py


In [103]:
image = torch.randn(1, 1, 5, 5) #задание изображения
kernel = torch.randn(1, 1, 3, 3) #задание ядра свёртки
#результат использования нашей функции Convolution2D
test1_output1 = torch.from_numpy(conv2D(image[0, 0].numpy(), kernel[0, 0].numpy()))

print("Результат использования нашей функции Convolution2D в тесте 1:")
print(test1_output1)
print("Результат использования функции Conv2d библиотеки PyTorch в тесте 1:")
test1_output2 = libConv2d(image, kernel)
print(test1_output2)

test1_output1 = test1_output1.to(test1_output2.dtype)

torch.allclose(test1_output1, test1_output2)

Результат использования нашей функции Convolution2D в тесте 1:
tensor([[ 4.9497,  0.5086, -5.7789],
        [ 1.3994,  3.1297,  0.4263],
        [-1.2416,  3.1127, -0.5508]], dtype=torch.float64)
Результат использования функции Conv2d библиотеки PyTorch в тесте 1:
tensor([[[[ 4.9497,  0.5086, -5.7789],
          [ 1.3994,  3.1297,  0.4263],
          [-1.2416,  3.1127, -0.5508]]]])


True

In [104]:
image = torch.randn(1, 1, 4, 4) #задание изображения
kernel = torch.randn(1, 1, 2, 2) #задание ядра свёртки
#результат использования нашей функции Convolution2D
test1_output1 = torch.from_numpy(conv2D(image[0, 0].numpy(), kernel[0, 0].numpy(), stride = 2))

print("Результат использования нашей функции Convolution2D в тесте 1:")
print(test1_output1)
print("Результат использования функции Conv2d библиотеки PyTorch в тесте 1:")
test1_output2 = libConv2d(image, kernel, stride = 2)
print(test1_output2)

test1_output1 = test1_output1.to(test1_output2.dtype)

torch.allclose(test1_output1, test1_output2)

Результат использования нашей функции Convolution2D в тесте 1:
tensor([[-0.3706, -0.0492],
        [-0.3375,  1.3711]], dtype=torch.float64)
Результат использования функции Conv2d библиотеки PyTorch в тесте 1:
tensor([[[[-0.3706, -0.0492],
          [-0.3375,  1.3711]]]])


True

In [101]:
image = torch.randn(1, 1, 6, 6) #задание изображения
kernel = torch.randn(1, 1, 3, 3) #задание ядра свёртки
#результат использования нашей функции Convolution2D
test1_output1 = torch.from_numpy(conv2D(image[0, 0].numpy(), kernel[0, 0].numpy(), stride = 2))

print("Результат использования нашей функции Convolution2D в тесте 1:")
print(test1_output1)
print("Результат использования функции Conv2d библиотеки PyTorch в тесте 1:")
test1_output2 = libConv2d(image, kernel, stride = 2)
print(test1_output2)

test1_output1 = test1_output1.to(test1_output2.dtype)

torch.allclose(test1_output1, test1_output2)

Результат использования нашей функции Convolution2D в тесте 1:
tensor([[-3.8708,  2.3698],
        [ 1.9609, -1.9370]], dtype=torch.float64)
Результат использования функции Conv2d библиотеки PyTorch в тесте 1:
tensor([[[[-3.8708,  2.3698],
          [ 1.9609, -1.9370]]]])


True